### ISSUE TITLE
PT 모드 키고 방 생성 시 영상 송출 종료 후 다시 전송 할때 영상으로 안나감, PT 모드 해제 하여도 동일함, 방 생성 후 PT 모드 키고 영상 송출 종료 후 다시 전송 할때도 동일 현상

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#100]

**Comment by benjamincho** [comment]
- 추가적인 재현경로가 필요함. 아래의 케이스로 인한 경우가 아니면 영상이 전송되고 있음

- 안드로이드 이슈
1. 프레젠테이션모드 활성화 후 아이폰에서 영상전송하다가 종료 후 영상을 다시 전송하는 데 
	안드로이드에서 영상전송을 선택하면 전송이 가능함.
2. 아이폰에서는 이후 프레젠테이션 모드이고, 안드로이드에서 영상이 들어오기 때문에 영상을 보내지 않음.	
3. 아이폰에서는 영상전송으로 패킷에 "*"을 보내는데 안드로이드에서 가끔 인식못하는 경우가 있음
	이 경우 안드로이드에서 영상전송을 한번 내보낸 후에는 안드로이드가 아이폰이 내보낸 패킷을 영상으로 인식함.
