### ISSUE TITLE
전체 뷰일때 메트릭스 모드로 돌아갈수 없음

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#106]

**Comment by benjamincho** [comment]
* 전체 뷰일때 메트릭스 모드로 돌아갈수 없음
- 아이폰의 전체뷰에서 매트릭스 모드를 최초에 막은 이유는 이미지 확대축소, 리모트컨트롤 등의 제스쳐 처리와 충돌이 
발생하여서임.
- 아이폰에서 전체뷰에서 참여자를 보는 중 매트릭스 모드로 돌아가는 경우 추가로 별도 처리하였음
	다만, 위의 이유로 애니매이션 효과는 구현할 수 없음.

**Comment by glotechlab** [comment]
해결
