### ISSUE TITLE
5명이상 참여할 경우 매트릭스 모두 화면 배치 조정. 현재 9분할 후 5명 표시. 6분할 후 5명 표시로.

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#111]

**Comment by benjamincho** [comment]
* 5명이상 참여할 경우 매트릭스 모두 화면 배치 조정. 현재 9분할 후 5명 표시. 6분할 후 5명 표시로.
- 이전에 문의시 PC기준으로 가이드 받아서 그대로 적용한 사항임
- 해당 이슈는 버그가 아니라 기능개선 요청사항임.
