### ISSUE TITLE
앱이 너무 자주 종료 됨

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#113]

**Comment by glotechlab** [comment]
참여자 변동이나, 영상 받다 중지 등 이벤트 발생 시 종료 될때도 있음

**Comment by glotechlab** [comment]
특정 케이스를 잡기가 어려운 부분이 있음. 이유없이 종료 되버리는 현상이 나옴

**Comment by glotechlab** [comment]
멀티뷰 구성 하다 종료되는경우도 있음

**Comment by benjamincho** [comment]
증상점검중이며, 바이너리 이슈에 대비해서 업데이트시 앱 삭제 후 재설치 요청드립니다.
