### ISSUE TITLE
방생성 -> 방옵션 -> 레코딩 -> 레코드를 참여자로 나타 남

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#137]
정상 결과 : 레코드를 참여자로 나타 내면 안됨

**Comment by benjamincho** [comment]
[서버 콜백] 12023TESTIOS1@RECORDER.20160614150653482.TESTIOS.ST.0AND5

닉네임 : @RECORDER.20160614150653482.TESTIOS.ST.0,
디바이스 : AND,
who아이디 : 5

- 레코딩 활성화시 서버에서 추가 방입장 멤버로 위와 같이 내려오고 있습니다. 정확한 가이드 요청드립니다.

**Comment by glotechlab** [comment]
@RECORDER 로 들어오는 거는 표현 안하는 거라고 문서에 적혀 있습니다.
확인 부탁 드립니다.
