### ISSUE TITLE
방생성 전 PT 모드 옵션 Off -> 방생성  -> PT 모드 On -> 방종료 -> 방생성 전 PT 모드 옵션 On 되어 있음

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#166]
정상 결과 : 방생성 PT 모드 옵션은 Default Off
로그 아웃 및 앱 종료 전까지 설정 한 옵션을 가져 감
방 입장 하여 설정한 PT 모드 옵션 과는 별개임

**Comment by benjamincho** [comment]
#138 과 반대되는 데 확인해 주세요.

**Comment by glotechlab** [comment]
방 생성 PT 옵션은 방 생성 후 PT 옵션 설정된 값과 연관 없습니다.

방 생성 PT 옵션은 로그인, 앱 종료 시 Default 값으로 설정 됩니다.
방 생성 PT 옵션은 로그아웃, 앱 종료 전 까지는 유지 됩니다.

방 생성 후 PT 옵션은 방 종료 시 Default 값으로 설정 됩니다.
방 생성 후 PT 옵션은 방 종료 전 까지는 유지 됩니다.
