### ISSUE TITLE
방입장 -> 참여자 영상탭 -> 카메라 오픈 -> 듀얼 뷰 -> Source 메뉴 선택 -> 사진 앨범 -> 닫기 버튼 없음

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#169]
정상 결과 : 닫기 버튼 있어야 함

**Comment by benjamincho** [comment]
사진앨범의 경우 라인 그리기 모드가 비활성화 되는 상단의 버튼을 선택해야 한다고 전달받았습니다.
확인해 주세요.

**Comment by glotechlab** [comment]
"사진앨범의 경우 라인 그리기 모드가 비활성화 되는 상단의 버튼을 선택해야 한다고 전달받았습니다.
확인해 주세요." 이 맞습니다
