### ISSUE TITLE
방생성 -> 레코딩 On -> 영상 녹화 안됨

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#182]
정상 결과 : 레코딩 되야 함

**Comment by benjamincho** [comment]
서버로 레코딩 요청을 전송하면 응답정보가 내려오는 게 없습니다.

테스트 중인 안드로이드 폰에서 레코딩을 요청해도 동일하게 서버로 부터 
@RECORDER 관련 정보가 내려오지 않는거 같습니다. 서버 확인 요청드립니다.

클라이언트 -> 서버 전송 값 : 
[Message Server WebSocket send] 14011TESTIOSSTVN.1
