### ISSUE TITLE
2016-05-03 Test 사항 입니다

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#2]
Test 장비 : 아이폰5, 아이패드2
Test 결과 :
1. 음성통신이 안됩니다. (말하기, 듣기)
2. IOS앱 에서 영상 전송이 안됩니다.
3. 영상 수신에서 이니셜 화면(초기화면)을 받고 그린 뒤 위에 변경된 화면을 그려 줘야 하는데
    변경된 영상만 그립니다.

**Comment by glotechlab** [comment]
Test 장비 : 아이패드 2
1. 영상 전송이 잘 안됩니다.- 카메라 오픈이 안도리 경우 있음
2. 전송과 뷰어를 동시에 할 경우 화면 더블 터치로 위치 변경이 안됩니다.
3. 2의 경우 우측 상단의 영역변경(나가기 옆) 버튼을 누르면 나가기가 실행 됩니다
4. 자신의 얼굴 아바타를 길게 누르면 화상전송 on/off이고, 짧게 누르면 영상 전송 on/off인데 둘 다 안됨
5. 방 조인 시 다른 참여자 영상 수신 시 터치를 하면 화상은 밑으로 내려가고 뷰어만 전체 화면으로 나와야 하는데 안됨
6. 참여자가 PT 모드로 설정 시 해당 영상만 전체 뷰어로 남아야 하는데 실행 안됨
7. 방을 나가거나, 앱 종료 시 질문창이 안나옵니다.
8. 방 생성시 방이름과 닉네임은 최종 입력값을 가지고 갔으면 합니다. 방 조인시에도 마찬가지입니다.(안드로이드 참조)
9. 전체적인 기능 확인 후 전달 바랍니다, 기능 적용 및 구현이 아주 불안합니다. 아이폰과 안드로이드, PC 세가지를 동시에 불여 테스트 바랍니다. 각각 문제가 없어야 합니다. 음성은 기본적으로 나와야 하는데 안들리고요..그리고 앱 실행 시 로그인 한 서버 주소를 상단에 뿌리는데 현재 나오는 주소가 다릅니다,
기능과 메세지등은 안드로이드 앱과 같아야 합니다. 방식이 다를 수는 있지만...같이 실행 해 비교 바랍니다
-백진호

**Comment by benjamincho** [comment]
수정사항(빌드버전 0.2.1)
1. 영상전송 관련 코드 수정(1. 영상 전송이 잘 안됩니다.- 카메라 오픈이 안도리 경우 있음)
2. 채팅룸 나가기버튼 좌측 여백 추가(2. 우측 상단의 영역변경(나가기 옆) 버튼 간격조절)
3. 영상 수신 관련 로직 수정 및 개선	
  (5. 방 조인 시 다른 참여자 영상 수신 시 터치를 하면 화상은 밑으로 내려가고 뷰어만 전체 화면으로 나와야 하는데 안됨)
  (6. 참여자가 PT 모드로 설정 시 해당 영상만 전체 뷰어로 남아야 하는데 실행 안됨)
4. 알림메세지 관련 추가 작업   
 1) 방종료시 수정함( 7. 방을 나가거나, 앱 종료 시 질문창이 안나옵니다.)
 2) 앱종료시는 별도 처리할 수 없습니다.
 3) 토스트메세지 적용 
5. 기타수정  (방 생성시 방이름과 닉네임은 최종 입력값을 가지고 갔으면 합니다. 방 조인시에도 마찬가지입니다. )
1) 방 생성시 방이름과 닉네임은 최종 입력값으로 기존에도 계속 가지고 있습니다.
2) 방 조인시 1)과 동일하게 수정
3) 방목록 상단 서버주소 수정 (9. 앱 실행 시 로그인 한 서버 주소)
4) 멤버 초대, 호출관련 수정
5) 방생성로직 수정(gps좌표 오차범위로 인한 방생성실패 방어코드 추가)
6) 파일저장 관련 수정 
7) 롱터치 이벤트 시점변경
6. 오디오 관련 수정 
7. 오픈소스 추가
- ReachablilitySwift
- Toast-Swift
