### ISSUE TITLE
전송중 최상단 메뉴에 창크기 조절 버튼

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#24]
1. 창크기 조절 버튼이 카메라 닫기가 됨
2. 창크기 조절 버튼은 기본 비활성화
3. 창크기 조절 버튼은 내가 전송중에 다른 전송화면 볼때 (듀얼뷰) 활성화
4. 창크기 조절 버튼은 듀얼뷰 화면의 크기 조절 (1~3단계 : Default, 2단계, 3단계) 버튼 누를때마다
1 → 2 → 3 → 1 → 2 → 3 순환

**Comment by benjamincho** [comment]
풀뷰 - 창크기 조절버튼 비활성화
듀얼뷰 - 활성화, 사이즈 변경(1, 2, 3)
(소스버튼, 창크기 조절버튼)
