### ISSUE TITLE
듀얼뷰 닫기

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#25]
1. 듀얼뷰 닫기는 전송자 리스트 화면 클릭시 닫기
2. 무빙뷰 영역이 매트릭스 영역을 벗어나면 듀얼뷰가 종료되어야 함

**Comment by benjamincho** [comment]
탭이벤트 관련 재정리 해서 받기로 했음 
더블탭 이벤트는 아이콘모드의 셀에 없음

**Comment by benjamincho** [comment]
#31, #32 신규등록해서 종료
