### ISSUE TITLE
전송 화면 캡쳐

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#26]
1. 전송 화면 캡쳐 시 Default 는 드로잉 입니다.
2. 드로잉 비 활성화 시 캡쳐 이미니 Moving 이 되야 합니다.

**Comment by glotechlab** [comment]
캡쳐 화면 종료는 드로잉 해제 후 종료 가능합니다. 'x' 표시 누르면 영상 전송 모드로 전환 됨

**Comment by benjamincho** [comment]
화면 무빙은 우측 상단의 아이콘을 터치해야 함. 
동작 확인하고 이슈 닫습니다.
