### ISSUE TITLE
아이콘 모드, 전체 화면 모드 전환

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#27]
1. 아이콘 모드에서 전체 화면 모드로 전환은 잘 됩니다
전체 화면 모드에서 사용자 리스트 드레그시 아이콘 모드로 전환 되야 합니다.

**Comment by glotechlab** [comment]
좌우 슬라이딩의 경우 참여자 전체 리스트가 화면에 표출 되고 다시 오른쪽으로 밀면 작은 화면으로 정렬이 됨. 각 화면 내용은 영상이나 PC 자료 전송 시에는 해당 화면이 나오고(자료공유와 화상 동사 전송 시에는 자료공유가 나옴) 화상만 전송 시에는 화상이 표시됨.  둘다 없을 경우 아바타 그림임. PC 사용자가 자료 공유와 화상을 동시에 보낼 경우 오른쪽 아이콘 모드일경우에는 자료 공유가 표시됨. PC 자료와 화상이 같이 표현되는 경우는 작은 아이콘모드 정렬에서 해당  PC 전송자의 공유 화면을 선택할 경우 뷰어 영역은 자료공유 화면이 나오고 오른쪽의 작은 참여자 리스트에는 화상이 나옴.

**Comment by benjamincho** [comment]
터치 이벤트가 아이콘모드 아이콘과 충돌하여서 아이콘모드에서 매트릭스 모드로 전환되는 
이벤트 처리 영역이 아이콘 모드 바깥의 매트릭스 영역에서 처리됩니다.
