### ISSUE TITLE
전체 화면 뷰잉 시 최상단 메뉴

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#28]
1. 뷰잉 시 최상단 메뉴는 카메라 로테이트, 카메라 오픈 버튼만 있어야 합니다.
2. 전송 메뉴와 뷰잉 메뉴는 다릅니다.

**Comment by benjamincho** [comment]
1. 본인화면 송출시가 아니고 전체화면 타인화면 수신시 소스, 카메라오픈버튼만 있어야 함

**Comment by benjamincho** [comment]
창조절버튼이 아닌, 카메라 오픈으로 변경해야 함
