### ISSUE TITLE
2016-05-09 Test 사항입니다.

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#3]
1. 방 생성 시 방이름의 최종 이름을 가지고 있는 부분
  - 자신이 입력한 방이름을 넣어주면 됩니다.
  - 지금은 서버의 들어오는 방이름을 표현하는것 같습니다.
2. 이어폰을 꽂은 상태로 방 생성시 스피커폰 아이콘이 살아 있음
3. 영상 수신 중 영상이 종료 되었을때 뷰어 화면이 자동 종료 안됨, 그로인해 이 영상 종료 후 영상을 전송할수 없음, 전에 본 뷰어 화면만 나옴
4. 방이 종료되었을때 자동으로 종료 안됨
5. 프리젠테이션 모드일때 두명이 화면을 전송 하고 있을때 한개의 뷰어에서 번갈아 가면서 뷰어화면이 나옴 
6. 아이폰에서 전송일때 아이폰 수신측에서는 프리젠테이션 모드가 아닐때도 프리젠테이션 모드라고 나옴
7. 카메라 오픈이 안될때가 있음
8. 아이폰에서 전송 화면의 최초 전송의 로테이트 포맷만으로 보냅니다
  - (ex 세로로 전송 하다 가로로 전송 하면 수신측에서 세로 포맷으로 가로 영상이 보임)
9. PC 에서 전송되는 화면의 Initial 화면을 뷰어에 그리지 않습니다
10. PC 에서 전송되는 화면을 Initial 화면에 위치를 고려하여 겹쳐서 그리지 않음
11. 멤버 초대 기능에서 전화번호 탭에서 검색 기능 안됨
12. 멤버 초대 기능에서 전화번호 승인을 묻고 승인 뒤에 전화번호가 최초에 한번 나오고 이후에 탭이 안나옴

**Comment by benjamincho** [comment]
해당 이슈들은 #4 ~ #12 에서 다시 기술되어있습니다.
