### ISSUE TITLE
테스트 2016-05-10 폰6 내용입니다

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#4]
아이폰6, 아이패드 에어 테스트 내용입니다(jhlee3d 계정)

1. 로그인은 되나 방생성 및 방 참여가 안됩니다.
2. 오류: 방 참여를 할 수 없습니다 메세지.
3. 오류: 방 생성을 할 수 없습니다 메세지
4. 방 생성 및 참여를 못해 테스트 불가능합니다
5. 내일 오시면 전체적인 점검을 해봤으면 합니다.
수고하세요--백진호

**Comment by benjamincho** [comment]
해당 이슈들은 #4 ~ #12 에서 다시 기술되어있습니다.
