### ISSUE TITLE
아이콘모드 셀의 경우 PC참여자의 영상과 화상이 동시에 올 경우 영상 우선 표현. 영상, 화상 교대로 보임(아이폰4S)

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#58]
1. pc는 화상, 영상이 다 전송됨
2. ss_nicknamelist 에 있는 참여자
- 아이콘 모드/매트릭스 모드에서는 화상은 무시하고
- 전체화면에서는 전체화면은 영상, 아이콘은 화상으로 처리

**Comment by benjamincho** [comment]
증상재현됨

**Comment by benjamincho** [comment]
#75와 동일이슈로 이슈 클로징
