### ISSUE TITLE
영상전송 중 캡쳐 시 캡쳐 화면이 안보임. 캡쳐 종료 시에도 영상이 안보이는 현상이 나옴.

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#63]
1. 캡쳐화면 정상동작함 
2. 캡쳐화면 종료시 영상전송 다시 진행 
3. 버튼 컬러 변경 (드로잉 모드가 연두색)
4. 드로인 모드시 닫기 버튼 없음

**Comment by benjamincho** [comment]
1. 캡쳐 관련 수정확인 
2. #80 이슈와 중복으로 이슈 클로징
