### ISSUE TITLE
비정상 종료시 기존 방에 재입장이 안됨_됐다 안됐다 함.

### ISSUE THREAD

**Issue by glotechlab** [benjamincho/GlotechISUS#90]

**Comment by benjamincho** [comment]
서버 메세지 
websocketDidReceiveMessage Received text: 12021TESTIOS0NickName already joined!!

**Comment by benjamincho** [comment]
서버이슈로 보이며 서버에서 확인한다고 했음

**Comment by benjamincho** [comment]
서버이슈로 이슈 종료
